config/routes.rb
Rails.application.routes.draw do
  resources :klasses, only: [:show, :index, :new, :create]
  resources :instructors, only: [:show, :index, :new, :create]
  resources :subjects, only: [:show, :index, :new, :create]
  resources :students, except: [:index]
  resources :reviews, except: [:index]

  root 'students#homepage'
  get "/login", to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/students', to: 'students#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/instructor.rb
class Instructor < ApplicationRecord
  has_many :klasses, dependent: :destroy
  has_many :subjects, through: :klasses, dependent: :destroy
  validates :name, presence: true, uniqueness: true

  def rating
    if !self.klasses.empty?
        rate = self.klasses.map {|k| k.average_overall}.select {|rating| rating.is_a?(Float)}
        if !rate.empty?
          (rate.inject(:+)) / (rate.length)
        end
    end
  end
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController
  before_action :rootmaker


  def show
    @instructor = Instructor.find(params[:id])
  end

  def index
    @instructors = Instructor.all
  end

  def new
    @instructor = Instructor.new
  end

  def create
    @instructor = Instructor.new(instructor_params)
    if @instructor.save
      redirect_to new_klass_path
    else render :new
    end
  end


    private


    def instructor_params
      params.require(:instructor).permit(:name)
    end
end

app/helpers/instructors_helper.rb
module InstructorsHelper
end

app/views/instructors/_instructor_form.html.erb
<%= form_for @instructor do |f| %>


<div class="row">

  <div class="col-sm-4">
    <%= f.label :name, "Name:"  %>
  </div>

  <div class="col-sm-3">
    <p>
    <%= f.text_field :name %>
    </p>
  </div>

</div>

<div class="row justify-content-center">


  <div class="row justify-content-center">
    <%= f.submit %>

  </div>
</div>
<% end %>

app/views/instructors/index.html.erb
<div class="container table-responsive">
<h1>All Instructors </h1>

  <table class="table table-hover rounded" id="index-tables">
    <tr>
      <th>Name</th>
      <th>Avg Class Rating</th>
    </tr>
    <% @instructors.each do |inst| %>
      <tr>
        <td><%= link_to inst.name, inst %></td>
        <% if inst.rating %>
        <td><%= inst.rating.round(2) %></td>
      <% else %>
        <td>--</td>
        <% end %>
      </tr>
    <% end %>
  </table>
  <span class="btn btn-light btn-md">
      <%= link_to "Create New Instructor", new_instructor_path %>
    </span>
</div>

app/views/instructors/new.html.erb
<div class="container jumbotron" id="center-div">

  <div class="row justify-content-md-center">
<h1>Create New Instructor</h1>

<%= render 'shared/errors', input: @instructor %>

<%= render 'instructor_form' %>

</div>

app/views/instructors/show.html.erb
<div class="container table-responsive">



<h1><%= @instructor.name %> </h1>

<% if @instructor.klasses.any? %>
  <table class = "table table-hover rounded" id="index-tables">
    <tr>
      <th>Subject</th>
      <th>Year</th>
      <th>Average Overall Rating</th>
    </tr>
      <% @instructor.klasses.each do |k| %>
      <tr>
        <td><%= link_to k.subject.name, subject_path(k.subject) %></td>
        <td><%= link_to k.year, k %></td>
        <td><%= k.average_overall %></td>
      </tr>
      <% end %>
  </table>
<% else %>
  There are no classes yet for this instructor <br><br>
  <span class="btn btn-light btn-md"><%= link_to "Create one now!", new_klass_path %></span>
<% end %><p></p>

<span class="btn btn-light btn-md "><%= link_to "All Instructors", instructors_path %></span>
</div>