config/routes.rb
Rails.application.routes.draw do
  resources :klasses, only: [:show, :index, :new, :create]
  resources :instructors, only: [:show, :index, :new, :create]
  resources :subjects, only: [:show, :index, :new, :create]
  resources :students, except: [:index]
  resources :reviews, except: [:index]

  root 'students#homepage'
  get "/login", to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/students', to: 'students#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/shared/_errors.html.erb
<% if input.errors.any? %>
  <ul>
    <% input.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
  </ul>
<% end %>

app/views/shared/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to "Accio Ratings", root_path, :class => "navbar-brand" %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">

    <% if session[:student_id] %>
    <ul class="navbar-nav">
      <li class="nav-item">
        <%= link_to "Instructors", instructors_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Subjects", subjects_path, :class => "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Create New Class", new_klass_path, :class => "nav-link" %>
      </li>
    </ul>

      <ul class="navbar-nav ml-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Account
          </a>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
            <%= link_to current_student.full_name, current_student, :class => "dropdown-item" %>
            <%= link_to "Log Out", logout_path, method: :delete, :class => "dropdown-item" %>
          </div>
        </li>
        </ul>
      <% end %>


  </div>
</nav>

app/views/shared/_review_form.html.erb
<div class="row">
  <div class="col">
    <%= render "shared/errors", input: @review %>
  </div>
</div>

<div class="row">
  <div class="col">
<%= form_for @review do |f| %>
  <%= f.hidden_field :klass_id %>
  <%= f.hidden_field :student_id, value: current_student.id %>
      <%= f.label :title, "Title:" %>
    </div>
    <div class="col">
      <%= f.text_field :title %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label :overall, "Overall:" %>
    </div>
    <div class="col">
      <%= f.select :overall, (1..5) %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label :difficulty, "Difficulty: (1 is least difficult)" %>
    </div>
    <div class="col">
      <%= f.select :difficulty, (1..5) %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label :intrigue, "Intrigue:" %>
    </div>
    <div class="col">
      <%= f.select :intrigue, (1..5) %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label :recomendation, "How likely are you to recomend to a classmate?" %>
    </div>
    <div class="col">
        <%= f.select :recommendation, (1..5) %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <%= f.label :content, "Write your review:" %><br>
      <%= f.text_area :content, size: "30x10" %>
    </div>
  </div>
  <div class="row">
    <div class="col">
      <%= f.submit %>
    </div>
<% end %>
</div>