config/routes.rb
Rails.application.routes.draw do
  resources :klasses, only: [:show, :index, :new, :create]
  resources :instructors, only: [:show, :index, :new, :create]
  resources :subjects, only: [:show, :index, :new, :create]
  resources :students, except: [:index]
  resources :reviews, except: [:index]

  root 'students#homepage'
  get "/login", to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/students', to: 'students#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/subject.rb
class Subject < ApplicationRecord
  has_many :klasses, dependent: :destroy
  has_many :instructors, through: :klasses, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/controllers/subjects_controller.rb
class SubjectsController < ApplicationController
  before_action :rootmaker


  def show
    @subject = Subject.find(params[:id])
  end

  def index
    @subjects = Subject.all
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.new(subject_params)
    if @subject.save
      redirect_to new_klass_path
    else render :new
    end
  end


  private

  def subject_params
    params.require(:subject).permit(:name)
  end
end

app/helpers/subjects_helper.rb
module SubjectsHelper
end

app/views/subjects/_subject_form.html.erb
<%= form_for @subject do |f| %>


<div class="row">

  <div class="col-sm-4">
    <%= f.label :name, "Name:"  %>
  </div>

  <div class="col-sm-3">
    <p>
    <%= f.text_field :name %>
    </p>
  </div>

</div>

<div class="row justify-content-center">


  <div class="row justify-content-center">
    <%= f.submit %>

  </div>
</div>
<% end %>

app/views/subjects/_subject_list.html.erb
<table class="table table-hover rounded" id="index-tables">
  <tr>
    <th>Instructor</th>
    <th>Year</th>
    <th>Average Overall Rating</th>
  </tr>
<% @subject.klasses.each do |klass| %>
  <tr>
    <td><%= link_to klass.instructor.name, instructor_path(klass.instructor)%> </td>
    <td><%= link_to klass.year, klass_path(klass)%></td>
    <td><%= klass.average_overall %></td>
  </tr>
<% end  %>
</table>

app/views/subjects/index.html.erb
<div class="container table-responsive">
  <h1>All Subjects </h1>

  <table class="table table-hover rounded" id="index-tables">
    <tr>
      <th>Name</th>
      <th>Classes</th>
    </tr>
    <% @subjects.each do |s| %>
      <tr>
        <td><%= link_to s.name, s %></td>
        <td><%= s.klasses.count %></td>
      </tr>
    <% end %>
  </table>
  <span class="btn btn-light btn-md"><%= link_to "Create New Subject", new_subject_path %></span>
</div>

app/views/subjects/new.html.erb
<div class="container jumbotron" id="center-div">

  <div class="row justify-content-md-center">
<h1>Create New Subject</h1>

<%= render 'shared/errors', input: @subject %>
<%= render 'subject_form', input: @subject %>

</div>
</div>

app/views/subjects/show.html.erb
<div class="container table-responsive">



<h1><%= @subject.name %></h1>

<% if @subject.klasses.length != 0 %>
  <%= render 'subject_list' %>
<% else %>
  There are no classes for this subject<br>
  <%= link_to "Create one now!", new_klass_path %>
<% end %><p></p>

<span class="btn btn-light btn-md">
  <%= link_to "All Subjects", subjects_path %>
  </span>
</div>