config/routes.rb
Rails.application.routes.draw do
  resources :klasses, only: [:show, :index, :new, :create]
  resources :instructors, only: [:show, :index, :new, :create]
  resources :subjects, only: [:show, :index, :new, :create]
  resources :students, except: [:index]
  resources :reviews, except: [:index]

  root 'students#homepage'
  get "/login", to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  get '/students', to: 'students#homepage'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/klasses_controller.rb
class KlassesController < ApplicationController
  before_action :rootmaker

  def show
    @klass = Klass.find(params[:id])
    @klass_reviews = @klass.reviews.select {|r| r.id}
  end

  def new
    @klass = Klass.new
  end

  def create
    @klass = Klass.new(klass_params)
    if @klass.save
      redirect_to @klass
    else render :new
    end
  end

  def index
  end



private

  def klass_params
    params.require(:klass).permit(:year, :subject_id, :instructor_id)
  end

end

app/helpers/klasses_helper.rb
module KlassesHelper
end

app/views/klasses/_nested_review_form.html.erb
<div class="review_form">

  <div class="" id="headingOne">
    <h2 class="mb-0">

        <% if !@klass.reviews.any? %>
          <h2>Be the first to review this class!</h2>
        <% else  %>
          <h2>Write a review for this class</h2>
        <% end %>
    </h2>
  </div>


  <div class="row">
    <div class="col">
        <%= form_for @klass.reviews.build do |f| %>
        <%= f.hidden_field :klass_id %>
        <%= f.hidden_field :student_id, value: current_student.id %>
          <div class="row">
            <div class="col">
              <%= f.label :title, "Title:" %>
            </div>
            <div class="col">
              <%= f.text_field :title %>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%= f.label :overall, "Overall:" %>
            </div>
            <div class="col">
              <%= f.select :overall, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%= f.label :difficulty, "Difficulty: (1 is least difficult)" %>
            </div>
            <div class="col">
              <%= f.select :difficulty, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%= f.label :intrigue, "Intrigue:" %>
            </div>
            <div class="col">
              <%= f.select :intrigue, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%= f.label :recomendation, "How likely are you to recomend to a classmate?" %>
            </div>
            <div class="col">
                <%= f.select :recommendation, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col">
              <%= f.label :content, "Write your review:" %><br>
              <%= f.text_area :content, size: "30x10" %>
            </div>
          </div>
          <div class="row">
            <div class="col">
              <%= f.submit %>
            </div>
          </div>
        <% end %>
        </div>
      </div>
</div>

app/views/klasses/_review_form.html.erb
<div class="review_form">

  <div class="" id="headingOne">
    <h2 class="mb-0">

        <% if !@klass.reviews.any? %>
          <h2>Be the first to review this class!</h2>
        <% else  %>
          <h2>Write a review for this class</h2>
        <% end %>
    </h2>
  </div>


  <div class="row">
    <div class="col-sm-11">
        <%= form_for @klass.reviews.build do |f| %>
        <%= f.hidden_field :klass_id %>
        <%= f.hidden_field :student_id, value: current_student.id %>
          <div class="row">
            <div class="col-md-3">
              <%= f.label :title, "Title:" %>
            </div>
            <div class="col-md-7">
              <%= f.text_field :title %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <%= f.label :overall, "Overall:" %>
            </div>
            <div class="col-md-6">
              <%= f.select :overall, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <%= f.label :difficulty, "Difficulty: (1 is least difficult)" %>
            </div>
            <div class="col-md-6">
              <%= f.select :difficulty, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <%= f.label :intrigue, "Intrigue:" %>
            </div>
            <div class="col-md-6">
              <%= f.select :intrigue, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-4">
              <%= f.label :recomendation, "How likely are you to recomend to a classmate?" %>
            </div>
            <div class="col-md-6">
                <%= f.select :recommendation, (1..5) %>
            </div>
          </div>

          <div class="row">
            <div class="col-md-10">
              <%= f.label :content, "Write your review:" %><br>
              <%= f.text_area :content, size: "30x10" %>
            </div>
          </div>
          <div class="row">
            <div class="col-sm-11">
              <%= f.submit %>
            </div>
          </div>
        <% end %>
        </div>
      </div>
</div>

app/views/klasses/_review_list.html.erb
<h3>Reviews - Click to read more!</h3>

  <div class="list-group">

    <% @klass_reviews.each_with_index do |r, ind| %>

      <a href="<%= review_path(r) %>" class="list-group-item list-group-item-action">
        <strong><%= "#{r.student.full_name} -- #{r.title}" %></strong>
        <p></p>
          Overall: <%= r.overall %> |
          Difficulty:   <%= r.difficulty %> |
          Intrigue: <%= r.intrigue %> |
          Would Recommend?  <%= r.recommendation %>
          </a>
    <% end %>
    
  </div>

app/views/klasses/new.html.erb
  <div class="container jumbotron" id="center-div">

  <div class="row justify-content-md-center">
    <h1>Add a new class to review!</h1>
      </div>
          <%= render 'shared/errors', input: @klass %>

        <div class="row justify-content-md-center">
          <%= form_for @klass do |f| %>
        <div class="row">

        <div class="col-sm-4">
          <%= f.label :subject_id, "Subject:"  %>
        </div>
        <div class="col-sm-4">
          <%= f.collection_select :subject_id, Subject.all.order(:name), :id, :name, prompt: true %><br>
        </div>
      </div>

      <div class="row">

        <div class="col-sm-4">
          <%= f.label :instructor_id, "Instructor:"  %>
        </div>

        <div class="col-sm-4">
          <%= f.collection_select :instructor_id, Instructor.all.order(:name), :id, :name %><br>
        </div>
      </div>
      <div class="row">

        <div class="col-sm-4">
          <%= f.label :year, "Year:" %>
        </div>

        <div class="col-sm-4">
          <%= f.select :year, (1990..Time.now.year) %><p></p>
        </div>

      </div>
        <div class="row justify-content-center">
          <div class="row justify-content-center">
            <%= f.submit 'Add Class' %>
          </div>
        </div>
            <% end %>

  </div>
  </div>

app/views/klasses/show.html.erb
<div class="container justify-content-center" id="fixed">
  <div class="row">
    <div class="col">
        <h1><%= link_to @klass.subject.name, subject_path(@klass.subject) %>, <%= @klass.year  %></h1>
        <h3>Taught by: <%= link_to @klass.instructor.name, instructor_path(@klass.instructor) %></h3>
      <div class="">



        <% if !@klass.reviews.empty? %>
          <table class="table table-sm table-dark rounded" id="klass-table">
            <thead>
              <tr>
                <th>Category</th>
                <th>Rating</th>
              </tr>
              </thead>
            <tr>
              <td>Overall</td>
              <td><%= @klass.average_overall %></td>
            </tr>
            <tr>
              <td>Difficulty</td>
              <td><%= @klass.average_diff %></td>
            </tr>
            <tr>
              <td>Intrigue</td>
              <td><%= @klass.average_intr %></td>
            </tr>
            <tr>
              <td>Would Recommend</td>
              <td><%= @klass.average_rec %></td>
            </tr>
          </table>
          <% else %>
          No reviews yet for this class.
          <% end %>

      </div>

      <div class="">
        <hr>
          <% if @klass.reviews.any? %>
            <%= render 'review_list' %>
          <% else %>
          <% end  %>
      </div>

      <div class="">
        <hr>
        <%= render 'nested_review_form' %>
      </div>

    </div>
  </div>
</div>